FROM node:20-alpine AS builder

WORKDIR /app
RUN npm install -g pnpm bun

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY src ./src
RUN pnpm build:relay

FROM node:20-alpine AS runner

WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production

CMD ["node", "dist/relay/index.js"]
